Fix build against recent sip/PyQt4:
qgsfiledownloader.sip:33:0:
src/gui/qgsfiledownloader.h:94:5: error: overriding non-deleted function 'virtual QgsFileDownloader::~QgsFileDownloader()'

RuntimeError: qgis._core cannot import type 'QList<QVariant>' from PyQt4.QtCore
(cherry picked from commit 85a0db24f32351f6096cd8282f03ad5c2f4e6ef5)

fixes #16071