Show actual proj error message in QgsCsException
The old code mistakenly assumed that proj error codes were all
values < 0, which they haven't been since proj 8.0

This meant all QgsCsExceptions were incorrectly including
"Error: Fallback transform failed", instead of the actual
error message from proj.

Now we get eg "Forward transform of (-7603859.000000, -7324441.000000)
Error: Invalid coordinate", which makes much more sense