FindQsci: removed the unused exception holder variable
master didn't build without that:
-- Found PyQt4 version: 4.10
  File "~/carina/Quantum-GIS/cmake/FindQsci.py", line 41
    except ImportError, e:
                      ^
SyntaxError: invalid syntax