qgssfcgalengine: Use source_location to replace __FUNCTION__ macros
`__FILE__`, `__FUNCTION__`, `__LINE__` are used by QgsSfcgalEngine to
display debug and error messages. However, it does not work with MSVC
compiler with the following error:

```
error C2457: '__FUNCTION__': predefined macro cannot appear outside of
a function body
```

This issue is fixed by using `source_location` from C++20.