[Processing] bugfix: intersection QGIS algorithm
fixing this by testing int_com.
```
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS2~1.17/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
self.processAlgorithm(progress)
File "C:/PROGRA~1/QGIS2~1.17/apps/qgis/./python/plugins\processing\algs\qgis\Intersection.py", line 100, in processAlgorithm
int_geom = QgsGeometry(int_com.difference(int_sym))
```

AttributeError: 'NoneType' object has no attribute 'difference'
(cherry picked from commit 3661bc39dbee312b3a0887ca80287cbc7b2260ec)