fix qt5 build dependencies
Building qt5 didn't work on debian stretch.

The first error was undefined reference to `openpty',
fixed by installing ``gnulib``.

Second error is ``sip_helpers/../core/sipAPI_core.h:11:17:
fatal error: sip.h: No such file or directory`` which is
fixed by installing python3-sip-dev

However, when python3-sip-dev is installed ``gnulib`` is
not required to get a successful build.

So, the simple fix is to just install python3-sip-dev